### ISSUE TITLE
sub-folder issue

### ISSUE THREAD

**Issue by DraigNET** [xanxTV/MDC-Panel#2]
If I have the MDC in a sub-folder (Example.com/mdc/) there are certain parts of the script that refer to the root folder, so I have to find the errors and update everything to refer to the sub folder. I wish there was an easier way of doing this.

**Comment by CXDezign** [comment]
The original project was ran on a sub domain. [mdc.example.com](url)
If you have the possibility, I would set it up in such a way.

The document root was set to the directory with the project files.
Meaning no relative paths were affected.
Otherwise you'll have to manually fix them as you have.

The project was never intended to be hosted outside of where it originated from, despite being open-sourced.
Therefore the support for different configurations aren't thought through, apologies.

The project is also no longer updated/supported. I'll close the issue after some time if there are no more responses.
😄

**Comment by Progefix** [comment]
is there a config where i can set de root dir? i got an redirection error page 404 when i try to go on a other page from the index file

**Comment by CXDezign** [comment]
The configuration for the root directory is configurable with an **Apache2 VirtualHost**.
In **A2** it's actually called `DocumentRoot`
https://httpd.apache.org/docs/2.4/vhosts/examples.html

Although, you can obviously use other web servers like **NGINX** to run the site.
Though the initial project was made specifically for **A2**.

In the `readme.md` of this project, there's a section about VirtualHosts.
https://github.com/CXDezign/MDC-Panel#2-virtual-hosts
This isn't an extensive guide, however, ChatGPT exists now, so if there's any issues, I'd advise to run any further questions regarding A2 or similar issues through that. 😁
